# BEGIN
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./test
    username: admin
    password: admin
    h2:
      console:
        enabled: true
# END
